services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USER=turnoadmin
      - DB_PASSWORD=13Demayo!
      - DB_NAME=TurnosUal

  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=13Demayo!
      - MARIADB_DATABASE=TurnosUal
      - MARIADB_USER=turnoadmin
      - MARIADB_PASSWORD=13Demayo!
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    # ... otras configuraciones
    ports:
      - "80:80"    # Para la redirección HTTP -> HTTPS
      - "443:443"  # **Este es el puerto HTTPS**
    volumes:
      # 1. Mapea el archivo de configuración de Nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # 2. Mapea la carpeta de certificados al contenedor Nginx
      - ./certs:/etc/nginx/certs:ro 
      # ... otros volúmenes (como tu frontend estático)
    depends_on:
      - backend
volumes:
  db_data: