services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USER=turnoadmin
      - DB_PASSWORD=13Demayo!
      - DB_NAME=TurnosUal
    restart: unless-stopped

  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=13Demayo!
      - MARIADB_DATABASE=TurnosUal
      - MARIADB_USER=turnoadmin
      - MARIADB_PASSWORD=13Demayo!
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
      - "4443:443"                    # Puerto HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
      - ./certs:/etc/nginx/certs     # Montar certificados
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  db_data: